getOptions > refactor code for reuse through multiple ESLibs
viivue/easy-select pull request #10
Opened 2023-01-04 06:50 UTC by vuquangpham

More detail at: https://github.com/viivue/wp-snippets/issues/25

2023-01-04 06:54 UTC, vuquangpham commented
I have forked this repository and created PR from it. So I can't set the assignee or reviewer for this PR. Sorry about that!

2023-01-10 06:54 UTC, phucbm requested changes
Make sure `getOptions` is identical to the [merged version](https://github.com/viivue/easy-tab-accordion/blob/8cc245e6c57c1db6050dfad87365bd80ce49a2f2/src/helpers.js#L199) from Easy Tab Accordion.

2023-01-12 07:43 UTC, vuquangpham commented on src/helpers.js
> +        else options.id = '';
I have added a small condition to remove the `id` from default options (for getting the id with the right priority below purpose).

2023-01-13 02:28 UTC, phucbm approved these changes
LGTM.

2023-01-13 02:29 UTC, merged